name: Run Local Script

on:
  repository_dispatch:
    types: [ios]
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5' # 根据需要更改 Python 版本

    - name: Make script executable
      run: chmod +x ./deploy.sh

    - name: Run the script
      run: bash ./deploy.sh
      
